### PR TITLE
fix(client): return correct type for foundry#WithOptions

### LINKED ISSUE #17: Foundry Client Issue
This code is creating a AnthropicClient when it should be creating a AnthropicFoundryClient. The with options creates an AnthropicClient and then the BeforeSend in the AnthropicFoundryClient is not called. Removing             ._client.WithOptions(options =>
                options with
                {
                    Timeout = options.Timeout ?? TimeSpan.FromMinutes(10),
                }
            ) fixes the issue but still problematic.

```
    public async Task<Message> Create(
        MessageCreateParams parameters,
        CancellationToken cancellationToken = default
    )
    {
        HttpRequest<MessageCreateParams> request = new()
        {
            Method = HttpMethod.Post,
            Params = parameters,
        };
        using var response = await this
            ._client.WithOptions(options =>
                options with
                {
                    Timeout = options.Timeout ?? TimeSpan.FromMinutes(10),
                }
            )
            .Execute(request, cancellationToken)
            .ConfigureAwait(false);
        var message = await response.Deserialize<Message>(cancellationToken).ConfigureAwait(false);
        if (this._client.ResponseValidation)
        {
            message.Validate();
        }
        return message;
    }
```

### PR DESCRIPTION
**Pull request by JPVenson**
fixes #17

### CODE REVIEW

**Review by packyg — DISMISSED** [review]

File: src/Anthropic/AnthropicClient.cs [hunk 1]
```diff
@@ -14,14 +14,29 @@ namespace Anthropic;
...
+        _messages = new(() => new MessageService(this));
+        _models = new(() => new ModelService(this));
+        _beta = new(() => new BetaService(this));
+    }
+
+    public AnthropicClient(ClientOptions options)
+        : this()
+    {
+        _options = options;
+    }
```
Comment (TomerAberbach) [inline src/Anthropic/AnthropicClient.cs]: Let's not move this. It's going to cause merge conflicts with codegen whenever we change the constructors in codegen

Comment (TomerAberbach) [reply src/Anthropic/AnthropicClient.cs]: If you think we should be moving the constructors elsewhere in the ordering for style reasons then let me know and I'll move them in codegen

File: src/Anthropic/AnthropicClient.cs [hunk 2]
```diff
@@ -301,7 +301,7 @@ static bool ShouldRetry(Exception e)
     {
         return e is IOException || e is AnthropicIOException;
     }
-
+
```
Comment (TomerAberbach) [inline src/Anthropic/AnthropicClient.cs]: nit: revert this as well

Comment (TomerAberbach) [reply src/Anthropic/AnthropicClient.cs]: Looks like you done it :)

**Review by TomerAberbach — APPROVED** [review]

File: src/Anthropic/AnthropicClient.cs (hunk 1 above)
Comment (JPVenson) [reply src/Anthropic/AnthropicClient.cs]: yes constructors generally come after private and static members but before all other methods and properties. See AnthropicFoundryClient.cs:22

Comment (TomerAberbach) [reply src/Anthropic/AnthropicClient.cs]: Cool, I'll file a ticket to do that, thanks :)
